// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzOvB7Ne74suyFW9xKR4EciqoXSxJTNfw',
    appId: '1:1001681847151:web:13b49ed76b738c5e511e9a',
    messagingSenderId: '1001681847151',
    projectId: 'recipefood-eb6f5',
    authDomain: 'recipefood-eb6f5.firebaseapp.com',
    storageBucket: 'recipefood-eb6f5.firebasestorage.app',
    measurementId: 'G-L2RRM6HLVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7YH1WZKIGfmeHHftzoZGulZC-eMBhydQ',
    appId: '1:1001681847151:android:bfc85839944eb6a5511e9a',
    messagingSenderId: '1001681847151',
    projectId: 'recipefood-eb6f5',
    storageBucket: 'recipefood-eb6f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-LLB_Y4Ib8R1R3-EbzXuLAWwtDi34pM',
    appId: '1:1001681847151:ios:4d0ce05f7c6b07aa511e9a',
    messagingSenderId: '1001681847151',
    projectId: 'recipefood-eb6f5',
    storageBucket: 'recipefood-eb6f5.firebasestorage.app',
    iosBundleId: 'com.example.recipeMakan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh-LLB_Y4Ib8R1R3-EbzXuLAWwtDi34pM',
    appId: '1:1001681847151:ios:4d0ce05f7c6b07aa511e9a',
    messagingSenderId: '1001681847151',
    projectId: 'recipefood-eb6f5',
    storageBucket: 'recipefood-eb6f5.firebasestorage.app',
    iosBundleId: 'com.example.recipeMakan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzOvB7Ne74suyFW9xKR4EciqoXSxJTNfw',
    appId: '1:1001681847151:web:ce7da9658b5be39c511e9a',
    messagingSenderId: '1001681847151',
    projectId: 'recipefood-eb6f5',
    authDomain: 'recipefood-eb6f5.firebaseapp.com',
    storageBucket: 'recipefood-eb6f5.firebasestorage.app',
    measurementId: 'G-R3J4CRRE9C',
  );

}